### ISSUE TITLE
[Question] Fatal Python error: "Segmentation fault" when using SparseML to prune Yolov5 model

### ISSUE THREAD

**Issue by LNTH** [neuralmagic/sparseml#1297] opened 2023-01-06 10:50 UTC
Hi, I'm trying to use SparseML to prune and quantize my Yolov5l6 model and facing this issue

My environment
```
# python version 3.8.13
conda install pytorch==1.12.1 torchvision==0.13.1 cudatoolkit=11.3 -c pytorch
pip install sparseml[torchvision]
pip install https://github.com/neuralmagic/yolov5/releases/download/nightly/yolov5-6.1.0-py3-none-any.whl
```

Train command
```
!sparseml.yolov5.train \
  --weights "YOLOv5/v7_101220223/weights/best.pt" \
  --data "data/v7/data.yaml" \
  --hyp "data/hyps/hyp.custom.yaml" \
  --recipe "zoo:cv/detection/yolov5-l/pytorch/ultralytics/coco/pruned80_quant-none" \
  --batch-size 8 \
  --cache \
  --imgsz 1280
```

Error log
```
/home/huy/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/utils/tensorboard/__init__.py:4: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if not hasattr(tensorboard, "__version__") or LooseVersion(
/home/huy/anaconda3/envs/yolov5/lib/python3.8/site-packages/botocore/httpsession.py:41: DeprecationWarning: 'urllib3.contrib.pyopenssl' module is deprecated and will be removed in a future release of urllib3 2.x. Read more in this issue: https://github.com/urllib3/urllib3/issues/2680
  from urllib3.contrib.pyopenssl import orig_util_SSLContext as SSLContext
/home/huy/anaconda3/envs/yolov5/lib/python3.8/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:326: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  np.bool8: (False, True),
/home/huy/anaconda3/envs/yolov5/lib/python3.8/site-packages/eventlet/support/greenlets.py:6: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  preserves_excinfo = (distutils.version.LooseVersion(greenlet.__version__)
/home/huy/.local/lib/python3.8/site-packages/requests_toolbelt/_compat.py:56: DeprecationWarning: 'urllib3.contrib.pyopenssl' module is deprecated and will be removed in a future release of urllib3 2.x. Read more in this issue: https://github.com/urllib3/urllib3/issues/2680
  from requests.packages.urllib3.contrib.pyopenssl \
/home/huy/anaconda3/envs/yolov5/lib/python3.8/site-packages/thop/profile.py:12: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if LooseVersion(torch.__version__) < LooseVersion("1.0.0"):
/home/huy/anaconda3/envs/yolov5/lib/python3.8/site-packages/seaborn/rcmod.py:82: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if LooseVersion(mpl.__version__) >= "3.0":
/home/huy/anaconda3/envs/yolov5/lib/python3.8/site-packages/setuptools/_distutils/version.py:346: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  other = LooseVersion(other)
[34m[1mwandb[0m: Currently logged in as: [33munknownhow[0m (use `wandb login --relogin` to force relogin)
[34m[1mtrain: [0mweights=/home/huy/projects/damage_detection_v2/yolov5/YOLOv5/v7_101220223/weights/best.pt, cfg=, data=/home/huy/projects/damage_detection_v2/data/v7/data.yaml, data_path=, hyp=data/hyps/hyp.custom.yaml, epochs=300, batch_size=8, gradient_accum_steps=1, imgsz=1280, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, evolve=None, bucket=, cache=ram, image_weights=False, device=, multi_scale=False, single_cls=False, optimizer=SGD, sync_bn=False, workers=8, project=yolov5_runs/train, name=exp, exist_ok=False, quad=False, cos_lr=False, label_smoothing=0.0, patience=0, freeze=[0], save_period=-1, local_rank=-1, entity=None, upload_dataset=False, bbox_interval=-1, artifact_alias=latest, recipe=zoo:cv/detection/yolov5-l/pytorch/ultralytics/coco/pruned80_quant-none, recipe_args=None, disable_ema=False, max_train_steps=-1, max_eval_steps=-1, one_shot=False, log_directory=None
[34m[1mgithub: [0mskipping check (not a git repository), for updates see https://github.com/ultralytics/yolov5
fatal: not a git repository (or any of the parent directories): .git
YOLOv5 🚀 2023-1-6 torch 1.12.1 CUDA:0 (NVIDIA GeForce RTX 3090, 24268MiB)

[34m[1mhyperparameters: [0mlr0=0.001, lrf=0.1, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.3, cls_pw=1.0, obj=0.7, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=1.5, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.3, translate=0.1, scale=0.6, shear=0.0, perspective=0.0, flipud=0.5, fliplr=0.5, mosaic=0.2, mixup=0.0, copy_paste=0.0
[34m[1mTensorBoard: [0mStart with 'tensorboard --logdir yolov5_runs/train', view at http://localhost:6006/
Fatal Python error: Segmentation fault

Current thread 0x00007f132c6b8340 (most recent call first):
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1166 in create_module
  File "<frozen importlib._bootstrap>", line 556 in module_from_spec
  File "<frozen importlib._bootstrap>", line 657 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 975 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 991 in _find_and_load
  File "/home/huy/anaconda3/envs/yolov5/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 62 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 843 in exec_module
  File "<frozen importlib._bootstrap>", line 671 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 975 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 991 in _find_and_load
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1042 in _handle_fromlist
  File "/home/huy/anaconda3/envs/yolov5/lib/python3.8/site-packages/tensorflow/python/__init__.py", line 36 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 843 in exec_module
  File "<frozen importlib._bootstrap>", line 671 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 975 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 991 in _find_and_load
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 961 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 991 in _find_and_load
  File "/home/huy/anaconda3/envs/yolov5/lib/python3.8/site-packages/tensorflow/__init__.py", line 37 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 843 in exec_module
  File "<frozen importlib._bootstrap>", line 671 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 975 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 991 in _find_and_load
  File "/home/huy/anaconda3/envs/yolov5/lib/python3.8/site-packages/tensorboard/compat/__init__.py", line 45 in tf
  File "/home/huy/anaconda3/envs/yolov5/lib/python3.8/site-packages/tensorboard/lazy.py", line 50 in load_once
  File "/home/huy/anaconda3/envs/yolov5/lib/python3.8/site-packages/tensorboard/lazy.py", line 97 in wrapper
  File "/home/huy/anaconda3/envs/yolov5/lib/python3.8/site-packages/tensorboard/lazy.py", line 65 in __getattr__
  File "/home/huy/anaconda3/envs/yolov5/lib/python3.8/site-packages/tensorboard/summary/writer/event_file_writer.py", line 72 in __init__
  File "/home/huy/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/utils/tensorboard/writer.py", line 75 in __init__
  File "/home/huy/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/utils/tensorboard/writer.py", line 276 in _get_file_writer
  File "/home/huy/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/utils/tensorboard/writer.py", line 246 in __init__
  File "/home/huy/anaconda3/envs/yolov5/lib/python3.8/site-packages/yolov5/utils/loggers/__init__.py", line 66 in __init__
  File "/home/huy/anaconda3/envs/yolov5/lib/python3.8/site-packages/yolov5/train.py", line 95 in train
  File "/home/huy/anaconda3/envs/yolov5/lib/python3.8/site-packages/yolov5/train.py", line 656 in main
  File "/home/huy/anaconda3/envs/yolov5/lib/python3.8/site-packages/yolov5/train.py", line 754 in run
  File "/home/huy/anaconda3/envs/yolov5/lib/python3.8/site-packages/sparseml/yolov5/scripts.py", line 49 in train
  File "/home/huy/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345 in wrapper
  File "/home/huy/anaconda3/envs/yolov5/bin/sparseml.yolov5.train", line 8 in <module>
```

Can anyone give suggestions to solve this error? Any help would be appreciated.

**Comment by KSGulin** [comment] 2023-01-06 14:19
Hi @LNTH, thanks for reporting this issue. It looks like the seg fault happens on initialization of the TensorBoard logger, when it tries to import either tensorflow or a tensorflow-like API. It seems you have TF installed - what version is it? It's difficult to determine the cause of the seg fault, but this sometimes arises due to a bad interaction between TF and CUDA stemming from a bad environment.

Luckily the solution should be simple - since TF is not needed to run YOLOv5 with SparseML, I'd recommend uninstalling it and trying again

**Comment by LNTH** [comment] 2023-01-09 04:19
Hi @KSGulin, since I couldn't uninstall Tensorflow, I created a new environment.

I'm facing a new error  `AttributeError: Can't get attribute 'DetectionModel' on <module 'models.yolo'`

```
YOLOv5 🚀 2023-1-9 torch 1.9.1 CPU

[34m[1mhyperparameters: [0mlr0=0.001, lrf=0.1, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.3, cls_pw=1.0, obj=0.7, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=1.5, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.3, translate=0.1, scale=0.6, shear=0.0, perspective=0.0, flipud=0.5, fliplr=0.5, mosaic=0.2, mixup=0.0, copy_paste=0.0
[34m[1mWeights & Biases: [0mrun 'pip install wandb' to automatically track and visualize YOLOv5 🚀 runs (RECOMMENDED)
[34m[1mTensorBoard: [0mStart with 'tensorboard --logdir YOLOv5', view at http://localhost:6006/
{
  "message": {
    "message": "AttributeError: Can't get attribute 'DetectionModel' on <module 'models.yolo' from '/home/huy/anaconda3/envs/sparseyolo/lib/python3.9/site-packages/yolov5/models/yolo.py'>",
    "extraInfo": {
      "py_callstack": [
        "  File \"/home/huy/anaconda3/envs/sparseyolo/bin/sparseml.yolov5.train\", line 8, in <module>\n    sys.exit(train())\n",
        "  File \"/home/huy/anaconda3/envs/sparseyolo/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py\", line 370, in wrapper\n    error_handler.record_exception(e)\n",
        "  File \"/home/huy/anaconda3/envs/sparseyolo/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/error_handler.py\", line 86, in record_exception\n    _write_error(e, self._get_error_file_path())\n",
        "  File \"/home/huy/anaconda3/envs/sparseyolo/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/error_handler.py\", line 26, in _write_error\n    \"py_callstack\": traceback.format_stack(),\n"
      ],
      "timestamp": "1673236927"
    }
  }
}
Traceback (most recent call last):
  File "/home/huy/anaconda3/envs/sparseyolo/bin/sparseml.yolov5.train", line 8, in <module>
    sys.exit(train())
  File "/home/huy/anaconda3/envs/sparseyolo/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 361, in wrapper
    return f(*args, **kwargs)
  File "/home/huy/anaconda3/envs/sparseyolo/lib/python3.9/site-packages/sparseml/yolov5/scripts.py", line 49, in train
    train_run(**vars(opt))
  File "/home/huy/anaconda3/envs/sparseyolo/lib/python3.9/site-packages/yolov5/train.py", line 754, in run
    main(opt)
  File "/home/huy/anaconda3/envs/sparseyolo/lib/python3.9/site-packages/yolov5/train.py", line 656, in main
    train(opt.hyp, opt, device, callbacks)
  File "/home/huy/anaconda3/envs/sparseyolo/lib/python3.9/site-packages/yolov5/train.py", line 122, in train
    model, extras = load_checkpoint(
  File "/home/huy/anaconda3/envs/sparseyolo/lib/python3.9/site-packages/yolov5/export.py", line 503, in load_checkpoint
    ckpt = torch.load(weights[0] if isinstance(weights, list) or isinstance(weights, tuple)
  File "/home/huy/anaconda3/envs/sparseyolo/lib/python3.9/site-packages/torch/serialization.py", line 607, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/huy/anaconda3/envs/sparseyolo/lib/python3.9/site-packages/torch/serialization.py", line 882, in _load
    result = unpickler.load()
  File "/home/huy/anaconda3/envs/sparseyolo/lib/python3.9/site-packages/torch/serialization.py", line 875, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute 'DetectionModel' on <module 'models.yolo' from '/home/huy/anaconda3/envs/sparseyolo/lib/python3.9/site-packages/yolov5/models/yolo.py'>
```

The commands I used to create new envs
```
conda create -n sparseyolo python=3.9
conda install pytorch==1.9.1 torchvision==0.10.1 cudatoolkit=11.3 -c pytorch -c conda-forge
pip install sparseml[torch,torchvision]
pip install sparsezoo
pip install https://github.com/neuralmagic/yolov5/releases/download/nightly/yolov5-6.1.0-py3-none-any.whl
```
And this is [the full requirements.txt](https://drive.google.com/file/d/1F_saIguxDKRiLIXny--aoPsd38bmF8KW/view?usp=sharing) using `pip freeze > requirements.txt`

The commands I used to train
```
sparseml.yolov5.train \
  --weights "/home/huy/projects/damage_detection_v2/yolov5/YOLOv5/v7_101220223/weights/best.pt" \
  --data "/home/huy/projects/damage_detection_v2/data/v7/data.yaml" \
  --hyp "data/hyps/hyp.custom.yaml" \
  --recipe "zoo:cv/detection/yolov5-l/pytorch/ultralytics/coco/pruned80_quant-none" \
  --batch-size 8 \
  --cache \
  --project "YOLOv5" --name "v7_sparse" --entity "samsum" \
  --imgsz 1280
```

**Comment by KSGulin** [comment] 2023-01-09 13:19
Was the checkpoint you're trying to produce also created with SparseML? Base yolov5 models are supported as well, but it's possible the original checkpoint was created with an incompatible version.

If you don't mind sharing, what is the motivation behind using your own pre-trained checkpoint? Is it pre-trained on the same data you're trying to train it on with this command? I ask, because in general we recommend starting with an already sparsified model trained on COCO and transfer learning it onto your custom data. You can modify the following two args in your command to get there:

`--weights zoo:cv/detection/yolov5-l/pytorch/ultralytics/coco/pruned80_quant-none?recipe_type=transfer_learn`
`--recipe zoo:cv/detection/yolov5-l/pytorch/ultralytics/coco/pruned80_quant-none?recipe_type=transfer_learn`

Under the hood, what this does is use the 80% pruned + quantized model, trained on COCO as your starting base model and applies the transfer learning recipe, resulting in a 80% pruned + quantized model trained on your custom dataset, while taking significantly less time than training starting from a dense model. Note the addition of the query `recipe_type=transfer_learn` to the end of the stub.

Note: We have just updated our SparseZoo with the latest yolov5 models developed by our research team. They're up to date with the latest yolov5 architecture and provide better speedups. However, we also just uncovered a bug with transfer learning this morning, so your updated command **will raise an error**. We're working on getting it fixed and I'll update here as soon as it is.

**Comment by LNTH** [comment] 2023-01-31 10:19
Sorry for the late reply @KSGulin 

Yes, my initial thought was to sparsify my custom-trained model and finetune again on the same dataset (similar to the quantization process)

So does the bug that you mentioned above been fixed?

**Comment by KSGulin** [comment] 2023-02-02 13:23
@LNTH yes the models have just been updated on SparseZoo. Make sure to also uninstall yolov5 and the latest version of our integration will be automatically downloaded for you when you run `sparseml.yolov5..`. Feel free to re-try your original command or to try a sparse transfer learning approach. 

The yolov5l 80% pruned model card doesn't have a transfer learning recipe, but the [80% pruned + quantized](https://sparsezoo.neuralmagic.com/models/cv%2Fdetection%2Fyolov5-l%2Fpytorch%2Fultralytics%2Fcoco%2Fpruned80_quant-none) one does. Check it out under the `recipes` tab to get the transfer command as well. Our latest models we've been quantizing with negligible drop in accuracy, so I usually suggest going with those. In this case, the pruned + quantized model is actually a bit more accurate than the pruned only

**Comment by LNTH** [comment] 2023-02-06 05:16
@KSGulin 

New error
```
Traceback (most recent call last):
  File "/home/huy/anaconda3/envs/sparseml/bin/sparseml.yolov5.train", line 8, in <module>
    sys.exit(train())
  File "/home/huy/anaconda3/envs/sparseml/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/home/huy/anaconda3/envs/sparseml/lib/python3.9/site-packages/sparseml/yolov5/scripts.py", line 49, in train
    train_run(**vars(opt))
  File "/home/huy/anaconda3/envs/sparseml/lib/python3.9/site-packages/yolov5/train.py", line 754, in run
    main(opt)
  File "/home/huy/anaconda3/envs/sparseml/lib/python3.9/site-packages/yolov5/train.py", line 656, in main
    train(opt.hyp, opt, device, callbacks)
  File "/home/huy/anaconda3/envs/sparseml/lib/python3.9/site-packages/yolov5/train.py", line 122, in train
    model, extras = load_checkpoint(
  File "/home/huy/anaconda3/envs/sparseml/lib/python3.9/site-packages/yolov5/export.py", line 550, in load_checkpoint
    sparseml_wrapper = SparseMLWrapper(
  File "/home/huy/anaconda3/envs/sparseml/lib/python3.9/site-packages/yolov5/utils/sparse.py", line 67, in __init__
    self.checkpoint_manager = ScheduledModifierManager.from_yaml(checkpoint_recipe) if checkpoint_recipe else None
  File "/home/huy/anaconda3/envs/sparseml/lib/python3.9/site-packages/sparseml/pytorch/optim/manager.py", line 285, in from_yaml
    modifiers = Modifier.load_list(yaml_str)
  File "/home/huy/anaconda3/envs/sparseml/lib/python3.9/site-packages/sparseml/pytorch/sparsification/modifier.py", line 90, in load_list
    return Modifier.load_framework_list(yaml_str, PYTORCH_FRAMEWORK)
  File "/home/huy/anaconda3/envs/sparseml/lib/python3.9/site-packages/sparseml/optim/modifier.py", line 319, in load_framework_list
    container = yaml.safe_load(yaml_str )
  File "/home/huy/anaconda3/envs/sparseml/lib/python3.9/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/home/huy/anaconda3/envs/sparseml/lib/python3.9/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/home/huy/anaconda3/envs/sparseml/lib/python3.9/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "/home/huy/anaconda3/envs/sparseml/lib/python3.9/site-packages/yaml/constructor.py", line 60, in construct_document
    for dummy in generator:
  File "/home/huy/anaconda3/envs/sparseml/lib/python3.9/site-packages/yaml/constructor.py", line 408, in construct_yaml_seq
    data.extend(self.construct_sequence(node))
  File "/home/huy/anaconda3/envs/sparseml/lib/python3.9/site-packages/yaml/constructor.py", line 129, in construct_sequence
    return [self.construct_object(child, deep=deep)
  File "/home/huy/anaconda3/envs/sparseml/lib/python3.9/site-packages/yaml/constructor.py", line 129, in <listcomp>
    return [self.construct_object(child, deep=deep)
  File "/home/huy/anaconda3/envs/sparseml/lib/python3.9/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/home/huy/anaconda3/envs/sparseml/lib/python3.9/site-packages/yaml/constructor.py", line 427, in construct_undefined
    raise ConstructorError(None, None,
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!pytorch.PerLayerDistillationModifier'
  in "<unicode string>", line 303, column 3:
    - !pytorch.PerLayerDistillationMod ...  
```
**Run command**
```
sparseml.yolov5.train \
  --cfg "/home/huy/projects/damage_detection_v2/yolov5/models/yolov5l.yaml" \
  --weights "zoo:cv/detection/yolov5-l/pytorch/ultralytics/coco/pruned80_quant-none?recipe_type=transfer_learn" \
  --recipe "zoo:cv/detection/yolov5-l/pytorch/ultralytics/coco/pruned80_quant-none?recipe_type=transfer_learn" \
  --data "/home/huy/projects/damage_detection_v2/data/v7/data.yaml" \
  --hyp "/home/huy/projects/damage_detection_v2/yolov5/data/hyps/hyp.custom.yaml" \
  --batch-size 8 \
  --cache \
  --project "YOLOv5" --name "v7_sparseml" --entity "samsum" \
  --imgsz 1280
```
**Environment**
```
python 3.9
pip install sparseml[torchvision]
conda install pytorch==1.12.1 torchvision==0.13.1 cudatoolkit=11.6 -c pytorch -c conda-forge
```

**Comment by KSGulin** [comment] 2023-02-13 15:58
Hi @LNTH, apologies for the late response. The `PerLayerDistillationModifier` is implemented in the current main and will be released with SparseML 1.4. To be able to use it prior to release, you'll need to install SparseML from source. This is because we've been using knowledge distillation to train the YOLOv5 models up on the Zoo

**Comment by bfineran** [comment] 2023-03-09 20:57
Hi @LNTH were you able to re-run this recipe against the latest version of SparseML?

**Comment by jeanniefinks** [comment] 2023-03-31 19:49
hi @LNTH As it's been sometime without a response, we'll close out this issue. But if you would like to continue the conversation and you were able to run the recipe against latest version of SparseML, please definitely re-open the ticket. 

Regards, Jeannie / Neural Magic

**Closed by jeanniefinks** 2023-03-31 19:49 UTC
