### ISSUE TITLE
Exported quantized model running slower than the pruned model on AVX2 supported CPU

### ISSUE THREAD

**Issue by VikasOjha666** [neuralmagic/sparseml#1364] opened 2023-02-04 14:34 UTC
**Describe the bug**
I have created a helper/library using sparseml and deepsparse for optimizing YOLO v7. After pruning the model is faster than the torch model when inference on the same CPU. However when I created a quantization recipe and exported the model the mode size also got reduced and it accepts uint8 as output but the model is slower than the pruned model. The CPU on which I was running supports int8 inference.

**Expected behavior**
It should be faster than the pruned model since it's both pruned and quantized.

**Environment**
Include all relevant environment information:
1.OS: Ubuntu 18.04
2.Python version: 3.8.10
3.DeepSparse version: 1.3
4.ML framework version(s) [e.g. torch 1.7.1]: torch 1.9
5.Other Python package versions [e.g. SparseML, Sparsify, numpy, ONNX]:Sparseml==1.3
6.CPU info - output of deepsparse/src/deepsparse/arch.bin or output of cpu_architecture() as follows:

**To Reproduce**
Run the notebook Inference_speed_between_tiny_YOLO_v7_pruned_and_quantized.ipynb  for checking inference and tiny_YOLO_v7_SparseML_integration_version_2_quantized.ipynb file for model training in the attached zip file with the recipes included in the zip.

**Errors**
No errors generated and model export is being done through SparseML exporter only.

Zip file with models and notebooks:
[tiny_yolov7_issue_resource_04_02.zip](https://github.com/neuralmagic/sparseml/files/10608872/tiny_yolov7_issue_resource_04_02.zip)

@shubhra @tlrmchlsmth @tdg5 @bfineran @KSGulin @corey-nm

**Comment by jeanniefinks** [comment] 2023-03-01 22:08
Hi @VikasOjha666 
I believe this is a duplicate of https://github.com/neuralmagic/deepsparse/issues/877 so I will close this one out. We can continue the conversation there. Thank you! 
Jeannie / Neural Magic

**Closed by jeanniefinks** 2023-03-01 22:08 UTC
Labels: bug
