### ISSUE TITLE
PyTorch Lightning - RuntimeError: cannot register a hook on a tensor that doesn't require gradient

### ISSUE THREAD

**Issue by clementpoiret** [neuralmagic/sparseml#1438] opened 2023-03-15 11:18 UTC
**Describe the bug**

When trying to use a SparseML callback with Pytorch Lightning, the following error is raised `RuntimeError: cannot register a hook on a tensor that doesn't require gradient`.
Please note I use a local copy of PyTorch lightning bolt SparseMLCallback because their _TORCH_MAX_VERSION does not match yours (I've made a PR for it to allow PT < 1.13.100. The only difference if that I do not check the `torch.__version__`

**Expected behavior**
It should train :)

**Environment**
Include all relevant environment information:
1. OS [e.g. Ubuntu 18.04]: Arch Linux
2. Python version [e.g. 3.7]: 3.9.15
3. SparseML version or commit hash [e.g. 0.1.0, `f7245c8`]: 1.5.0.20230315
4. ML framework version(s) [e.g. torch 1.7.1]: Torch 1.12.1
5. Other Python package versions [e.g. SparseZoo, DeepSparse, numpy, ONNX]:
6. Other relevant environment information [e.g. hardware, CUDA version]: I tried only on CPU

**To Reproduce**
Exact steps to reproduce the behavior:

Just run the training.py of this repo: https://github.com/clementpoiret/sparseml_register_hook_bug/

Pytorch Lightning SparseMLCallback hasn't been updated for a while, maybe its way to do is outdated?

**Errors**

```
/home/cp264607/anaconda3/envs/SparseML/lib/python3.9/site-packages/lightning_fabric/accelerators/cuda.py:219: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")
/home/cp264607/anaconda3/envs/SparseML/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py:737: UserWarning: You passed `Trainer(accelerator='cpu', precision=16)` but native AMP is not supported on CPU. Using `precision='bf16'` instead.
  rank_zero_warn(
Using bfloat16 Automatic Mixed Precision (AMP)
GPU available: False, used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Loading `train_dataloader` to estimate number of stepping batches.
/home/cp264607/anaconda3/envs/SparseML/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:224: PossibleUserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 12 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(

  | Name     | Type         | Params
------------------------------------------
0 | backbone | EfficientNet | 20.2 M
1 | loss     | MSELoss      | 0     
------------------------------------------
355 K     Trainable params
19.8 M    Non-trainable params
20.2 M    Total params
80.812    Total estimated model params size (MB)
Sanity Checking: 0it [00:00, ?it/s]/home/cp264607/anaconda3/envs/SparseML/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:224: PossibleUserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 12 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
Epoch 0:   0%|                                                                 | 0/16 [00:00<?, ?it/s]Traceback (most recent call last):
  File "<stdin>", line 13, in <module>
  File "/home/cp264607/anaconda3/envs/SparseML/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "/home/cp264607/anaconda3/envs/SparseML/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/cp264607/anaconda3/envs/SparseML/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/home/cp264607/anaconda3/envs/SparseML/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1103, in _run
    results = self._run_stage()
  File "/home/cp264607/anaconda3/envs/SparseML/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1182, in _run_stage
    self._run_train()
  File "/home/cp264607/anaconda3/envs/SparseML/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1205, in _run_train
    self.fit_loop.run()
  File "/home/cp264607/anaconda3/envs/SparseML/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/cp264607/anaconda3/envs/SparseML/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 267, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/home/cp264607/anaconda3/envs/SparseML/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/cp264607/anaconda3/envs/SparseML/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 213, in advance
    batch_output = self.batch_loop.run(kwargs)
  File "/home/cp264607/anaconda3/envs/SparseML/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/cp264607/anaconda3/envs/SparseML/lib/python3.9/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 88, in advance
    outputs = self.optimizer_loop.run(optimizers, kwargs)
  File "/home/cp264607/anaconda3/envs/SparseML/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/cp264607/anaconda3/envs/SparseML/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 202, in advance
    result = self._run_optimization(kwargs, self._optimizers[self.optim_progress.optimizer_position])
  File "/home/cp264607/anaconda3/envs/SparseML/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 249, in _run_optimization
    self._optimizer_step(optimizer, opt_idx, kwargs.get("batch_idx", 0), closure)
  File "/home/cp264607/anaconda3/envs/SparseML/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 370, in _optimizer_step
    self.trainer._call_lightning_module_hook(
  File "/home/cp264607/anaconda3/envs/SparseML/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1347, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/home/cp264607/anaconda3/envs/SparseML/lib/python3.9/site-packages/pytorch_lightning/core/module.py", line 1744, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/home/cp264607/anaconda3/envs/SparseML/lib/python3.9/site-packages/pytorch_lightning/core/optimizer.py", line 169, in step
    step_output = self._strategy.optimizer_step(self._optimizer, self._optimizer_idx, closure, **kwargs)
  File "/home/cp264607/anaconda3/envs/SparseML/lib/python3.9/site-packages/pytorch_lightning/strategies/strategy.py", line 234, in optimizer_step
    return self.precision_plugin.optimizer_step(
  File "/home/cp264607/anaconda3/envs/SparseML/lib/python3.9/site-packages/pytorch_lightning/plugins/precision/native_amp.py", line 68, in optimizer_step
    return super().optimizer_step(
  File "/home/cp264607/anaconda3/envs/SparseML/lib/python3.9/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 119, in optimizer_step
    return optimizer.step(closure=closure, **kwargs)
  File "/home/cp264607/anaconda3/envs/SparseML/lib/python3.9/site-packages/sparseml/pytorch/optim/manager.py", line 172, in step
    return self._perform_wrapped_step(*args, **kwargs)
  File "/home/cp264607/anaconda3/envs/SparseML/lib/python3.9/site-packages/sparseml/pytorch/optim/manager.py", line 209, in _perform_wrapped_step
    self._wrapped_manager.update(
  File "/home/cp264607/anaconda3/envs/SparseML/lib/python3.9/site-packages/sparseml/pytorch/optim/manager.py", line 589, in update
    mod.scheduled_update(module, optimizer, epoch, steps_per_epoch)
  File "/home/cp264607/anaconda3/envs/SparseML/lib/python3.9/site-packages/sparseml/pytorch/sparsification/modifier.py", line 620, in scheduled_update
    self.update(module, optimizer, epoch=epoch, steps_per_epoch=steps_per_epoch)
  File "/home/cp264607/anaconda3/envs/SparseML/lib/python3.9/site-packages/sparseml/pytorch/sparsification/modifier.py", line 452, in wrapper
    out = func(*args, **kwargs)
  File "/home/cp264607/anaconda3/envs/SparseML/lib/python3.9/site-packages/sparseml/pytorch/sparsification/pruning/modifier_pruning_base.py", line 354, in update
    self.check_mask_update(module, epoch, steps_per_epoch)
  File "/home/cp264607/anaconda3/envs/SparseML/lib/python3.9/site-packages/sparseml/pytorch/sparsification/pruning/modifier_pruning_base.py", line 374, in check_mask_update
    self._module_masks.enabled = True
  File "/home/cp264607/anaconda3/envs/SparseML/lib/python3.9/site-packages/sparseml/pytorch/sparsification/pruning/mask_params.py", line 227, in enabled
    self._create_hooks()
  File "/home/cp264607/anaconda3/envs/SparseML/lib/python3.9/site-packages/sparseml/pytorch/sparsification/pruning/mask_params.py", line 515, in _create_hooks
    self._gradient_hooks[idx] = param.register_hook(
  File "/home/cp264607/anaconda3/envs/SparseML/lib/python3.9/site-packages/torch/_tensor.py", line 430, in register_hook
    raise RuntimeError("cannot register a hook on a tensor that "
RuntimeError: cannot register a hook on a tensor that doesn't require gradient
```

**Additional context**
Add any other context about the problem here. Also include any relevant files.

**Comment by bfineran** [comment] 2023-03-15 20:15
Hi @clementpoiret thanks for the clear repo with reproduction steps.

1. We should be supporting torch 1.13 on the nightly version you are on - are you still seeing an error with torch 1.13? (https://github.com/neuralmagic/sparseml/blob/a715e1afce27cc851ebeedee60294f9136ccc720/src/sparseml/pytorch/base.py#L52)
2. SparseML pruners use torch hooks under the hood to enforce sparsity during training. These hooks require the parameter have `requries_grad=True`.  Could you check which parameters in your module that are targeted by the recipe at initialization time don't have requires grad on?  If it's a single layer that isn't meant to be targeted for backprop, then we can exclude it from the recipe. If for some reason the entire module doesn't have requires grad enabled, we can try enabling it before initializing sparseml.

**Comment by clementpoiret** [comment] 2023-03-16 09:03
@bfineran it happens also with torch==1.13.1. 

I checked parameters with requires_grad==False
```python
for name, param in model.named_parameters():
    if not param.requires_grad:
        print(name)
```

I got every parameter of the backbone except my custom classifier. So in my model, I have done:

```python
self.backbone = registry.create(model_name, pretrained=pretrained)

# Set requires_grad for backbone to True
for param in self.backbone.parameters():
    param.requires_grad = True
```

Printing all parameters with requires_grad==False returns nothing after that, but the problem stays the same: `RuntimeError: cannot register a hook on a tensor that doesn't require gradient`

Maybe it comes from that?

```yaml
  - !TrainableParamsModifier
    start_epoch: 0.0
    end_epoch: eval(num_epochs)
    trainable: false
    params: __ALL__
```

**Comment by clementpoiret** [comment] 2023-03-16 09:27
A simple workaround I found is to pass the register_hook call if requires_grad is false, where

```python
def _create_hooks(self):
    for idx, (param, layer) in enumerate(zip(self._params, self._layers)):
       ...
        if self._gradient_hooks[idx] is None:
            self._gradient_hooks[idx] = param.register_hook(
                partial(self._hook_mask_gradient, idx))
```

becomes

```python
def _create_hooks(self):
    for idx, (param, layer) in enumerate(zip(self._params, self._layers)):
       ...
        if self._gradient_hooks[idx] is None:
            self._gradient_hooks[idx] = param.register_hook(
                partial(self._hook_mask_gradient,
                        idx)) if param.requires_grad else None
```

If, according to you, it's the way to go, I can open a PR. But I don't know how to carefully test it.

**Comment by jeanniefinks** [comment] 2023-06-06 18:41
Hi @clementpoiret 
We've continued this thread in PR #1463 - let us know either way, thanks!
Best, Jeannie / Neural Magic

**Comment by bfineran** [comment] 2023-07-12 20:10
Hi @clementpoiret closing this for now since the branch hasn't been updated for a few months. Happy to circle back anytime.

**Closed by bfineran** 2023-07-12 20:10 UTC
Labels: bug
