### ISSUE TITLE
Error when training yolov8-seg in validators.py

### ISSUE THREAD

**Issue by Landaunn** [neuralmagic/sparseml#1510] opened 2023-04-05 13:21 UTC
Hi!
**Describe the bug**
I used `sparseml-nightly`  `version 1.5.0.20230404` , but I got an error after passing the first epoch of yolov8 segmentation training, which is in the file `sparseml/yolov8/validators.py` .

**Environment**
1. OS: Ubuntu 20.04.1
2. Python version: 3.8.10
3. SparseML version or commit hash: sparseml-nightly 1.5.0.20230404
4. ML framework version(s): torch 1.9.1

**Errors**
<img width="1395" alt="Снимок экрана 2023-04-05 в 16 14 36" src="https://user-images.githubusercontent.com/65294962/230092799-d77e9ece-b120-4687-9207-ec9d23dc9b41.png">

<img width="291" alt="Снимок экрана 2023-04-05 в 15 59 46" src="https://user-images.githubusercontent.com/65294962/230092834-96e3ffd6-a11c-4512-a7b8-93bee4cda247.png">

<img width="416" alt="Снимок экрана 2023-04-05 в 16 41 23" src="https://user-images.githubusercontent.com/65294962/230098588-e9d0276b-9fcc-4d4d-b839-3b4f079c3576.png">

**Comment by dbogunowicz** [comment] 2023-04-13 03:55
@Landaunn yes, this has come to our attention lately. We know the root cause and will be patching it asap.

**Comment by dbogunowicz** [comment] 2023-04-14 10:57
Hey, @Landaunn the fix is in #1522 . We will probably land it today, but if you wish, you can already introduce those changes locally to your repo.

**Closed by dbogunowicz** 2023-04-14 10:57 UTC
Labels: bug
